format = """
$username@$hostname $directory\
$git_branch\
$git_state\
$git_status\
$fill\
$docker_context\
$nodejs\
$rust\
$golang\
$php\
$bun\
$python\
$java\
$c\
$conda\
$zig\
$shell $cmd_duration $jobs $time\
\n$character\
"""

add_newline = true
command_timeout = 3600000
palette = "catppuccin_mocha"

[fill]
symbol = ' '
style = 'bold black'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.gentleman]
text = "#F3F6F9"
red = "#CB7C94"
green = "#B7CC85"
yellow = "#FFE066"
blue = "#7FB4CA"
mauve = "#A3B5D6"
pink = "#FF8DD7"
teal = "#7AA89F"
peach = "#DEBA87"
subtext0 = "#5C6170"
overlay0 = "#232A40"
rosewater = "#E0C15A"
flamingo = "#FF8DD7"
maroon = "#C4746E"
lavender = "#B99BF2"
subtext1 = "#8A8FA3"
overlay2 = "#313342"
overlay1 = "#191E28"
surface2 = "#27345C"
surface1 = "#232A40"
surface0 = "#191E28"
base = "none"
mantle = "#06080f"
crust = "#06080f"

[shell]
disabled = false
format = '[ $indicator]($style) '
style = 'fg:purple'

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false

[hostname]
ssh_only = false
style = "bold yellow"
format = "[$hostname]($style)"

[os]
format = "[($symbol)]($style)"
style = "bold red"
disabled = false

[os.symbols]
Arch = ' '
Unknown = ' '

[memory_usage]
symbol = "󰍛 "

[jobs]
symbol = " "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[character]
success_symbol = "[➜](fg:green)"
error_symbol = "[✗](fg:red)"

[username]
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"
show_always = true

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[cmd_duration]
min_time = 5_000
show_milliseconds = false
format = "[ $duration]($style)"
style = "fg:240"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style)"
style = "bold bright-purple"

[git_status]
format = ' $all_status$ahead_behind$diverged'
staged     = '[ ](bold green)'
modified   = '[ ](bold yellow)'
renamed    = '[ ](bold yellow)'
deleted    = '[ ](bold red)'
stashed    = '[󰜦 ](bold bright-purple)'
untracked  = '[ ](bold bright-purple)'
conflicted = '[ ](bold red)'
up_to_date = '[ ](bold green)'
ahead = '[⇡${count}](bold green)'
behind = '[⇣${count}](bold red)'
diverged = '[ ](bold red)([⇡${ahead_count} ](bold green)[⇣${behind_count}](bold red))'

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\) '
style = "bright-purple"
cherry_pick = '[ PICKING](bold red)'
merge = '[󰦦 MERGING](bold red)'
rebase = '[󰦦 REBASING](bold red)'

[git_commit]
commit_hash_length = 7
tag_symbol = '󰓹 '
disabled = false

[docker_context]
symbol = ""
detect_files = [ "docker-compose.yml", "docker-compose.yaml", "Dockerfile" ]

[python]
disabled = false
format = "[$symbol$pyenv_prefix($version)( $virtualenv)](fg:peach)"
symbol = " "
version_format = "$raw"

[java]
format = '[[ $symbol ($version) ](fg:red)]($style)'
version_format = "$raw"
symbol = " "
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:blue)]($style)'
symbol = " "
version_format = "$raw"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:peach)]($style)'
version_format = "$raw"
disabled = false

[bun]
version_format = "$raw"
format = '[[ $symbol ($version) ](fg:text)]($style)'
disabled = false

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:green)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:red)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:teal)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:peach)]($style)'

[time]
disabled = false
style = "fg:240"
format = "[$time]($style)"
